
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: ingabire
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: search_app_development

test:
  <<: *default
  database: search_app_test

production:
  <<: *default
  database: search_app_production
  username: postgres
  password: <%= ENV["RECIPE_DATABASE_PASSWORD"] %> 