
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV["DB_PASSWORD"] %> 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: search_app_development
  username: postgres
  password: ingabire

test:
  <<: *default
  database: search_app_test
  username: postgres
  password: ingabire

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>