article = Article.create(text: 'hello world, how are you?')
article = Article.create(text: 'what is a good car')
article = Article.create(text: 'what is a')
article = Article.create(text: 'how is emil harjic doing')
article = Article.create(text: 'howis emil harjic')
article = Article.create(text: 'how is')
article = Article.create(text: 'hello')
article = Article.create(text: 'hello world')